export const SCREENS = {
  // Auth
  Login: "Login",
  ChooseLanguage: "ChooseLanguage",
  ResetPassword: "ResetPassword",
  CreateYourAccount: "CreateYourAccount",
  VerifyYourEmail: "VerifyYourEmail",
  CreateYourPassword: "CreateYourPassword",
  StepOne: "StepOne",
  StepTwo: "StepTwo",
  StepThree: "StepThree",
  StepFour: "StepFour",
  StepFive: "StepFive",
  StepSix: "StepSix",
  StepSeven: "StepSeven",
  StepEight: "StepEight",
  StepNine: "StepNine",
  StepTen: "StepTen",
  ProfileDetails: "ProfileDetails",
  StepYesNoFlaxed: "StepYesNoFlaxed",
  StepCountScreen: "StepCountScreen",

  // Bottom Tab Navigation
  TabHome: "TabHome",
  TabHub: "TabHub",
  TabCommunity: "TabCommunity",
  TabExplorer: "TabExplorer",
  TabProfile: "TabProfile",

  // Main Stack Navigation
  AuthRoutes: "AuthRoutes",
  TabRoutes: "TabRoutes",
  NavigationRoutes: "NavigationRoutes",

  // Stack Navigation
  Explore: "Explore",
  ExploreDetails: "ExploreDetails",
  AccountSettings: "AccountSettings",
  Security: "Security",
  Language: "Language",
  DeleteAccount: "DeleteAccount",
  CreatePost: "CreatePost",
  ReourceDetails: "ReourceDetails",
  Chat: "Chat",
  Subscribe: "Subscribe",
  ChooseTier: "ChooseTier",
  BlockedUser: "BlockedUser",
  ReportUser: "ReportUser",
  Notification: "Notification",
  ChatUserList: "ChatUserList",
  ReportPost: "ReportPost",
  Post: "Post",
  EditProfileDetails: "EditProfileDetails",
  ProfilePicture: "ProfilePicture",
  Music: "Music",
};
